/* 전 학과 목록 — `GET /depts` 폴백 겸 입력 화면 소스.
   data/depts/*.json(P1 파이프라인 산출물)에서 생성했다. 손으로 고치지 말 것.
   API가 뜨면 lib/api.js의 getDepts()가 이 값을 대체한다.

   careers  = 교육과정표 인재양성유형(`talent_types`). **과목에 붙어 있는 라벨**이라
              로드맵을 역산할 수 있는 유일한 값이고, 서버 검증도 이걸 본다.
   promoted = 학과 소개 페이지가 홍보하는 진로. 과목과 안 이어져 있어서 로드맵에는
              못 쓴다. 진로↔라벨 대조는 트랙 B 리포트가 맡는다 (이슈 #25). */

export const DEPTS = [
  { id: "swcontent", name: "AI게임소프트웨어학과", years: 3, tier: 2,
    careers: ["인공지능게임소프트웨어개발"],
    promoted: ["게임프로그래머", "게임그래픽디자이너", "게임기획자", "모바일 앱 개발자", "소프트웨어 개발자", "서버프로그래머", "2D/3D 컴퓨터그래픽 디자이너"],
    majorCredits: 75, majorRequired: 66 },
  { id: "AI미디어디자인학과", name: "AI미디어디자인학과", years: 3, tier: 2,
    careers: ["AI영상미디어디자이너", "융합미디어기획자"],
    promoted: ["AI영상미디어디자이너", "융합미디어기획자"],
    majorCredits: 72, majorRequired: 66 },
  { id: "ceo", name: "경영학과", years: 2, tier: 2,
    careers: ["경영관리자"],
    promoted: ["경영관리자"],
    majorCredits: 63, majorRequired: 45 },
  { id: "publiccs", name: "공공행정서비스과", years: 2, tier: 2,
    careers: ["공공행정서비스"],
    promoted: ["행정학연구원"],
    majorCredits: 54, majorRequired: 45 },
  { id: "mee", name: "기계공학과", years: 2, tier: 2,
    careers: ["AI 기반승강기설치및예지보전엔지니어", "AI 기반지능형설계엔지니어", "공통", "스마트팩토리및기계설비엔지니어"],
    promoted: ["국가기술 자격법에 의한 산업기사"],
    majorCredits: 53, majorRequired: 45 },
  { id: "droneinfo", name: "드론정보공학과", years: 2, tier: 2,
    careers: ["드론운용전문가"],
    promoted: ["드론운용전문가"],
    majorCredits: 43, majorRequired: 45 },
  { id: "mjccrw", name: "문예창작과", years: 2, tier: 2,
    careers: ["문학교사", "창작가", "출판〮편집〮홍보전문가"],
    promoted: ["문학교사", "독서 지도사", "논술 지도사", "글쓰기교사"],
    majorCredits: 63, majorRequired: 45 },
  { id: "medinfo", name: "보건의료정보과", years: 2, tier: 2,
    careers: ["보건교육사", "의료정보관리전문가", "의료정보관리전문가및보건교육사"],
    promoted: ["보건교육사", "의료정보관리전문가", "의료정보관리전문가및보건교육사"],
    majorCredits: 51, majorRequired: 45 },
  { id: "rem", name: "부동산경영과", years: 2, tier: 2,
    careers: ["건물관리사", "부동산공급기능인", "부동산중개사", "부동산중개사·건물관리사·부동산공급기능인"],
    promoted: ["건물관리사", "부동산공급기능인", "부동산중개사", "부동산중개사·건물관리사·부동산공급기능인"],
    majorCredits: 45, majorRequired: 45 },
  { id: "뷰티매니지먼트과메이크업네일전공", name: "뷰티매니지먼트과메이크업·네일전공", years: 2, tier: 2,
    careers: ["네일아티스트", "메이크업아티스트"],
    promoted: ["네일아티스트", "메이크업아티스트"],
    majorCredits: 63, majorRequired: 45 },
  { id: "뷰티매니지먼트과방송스타일디렉터전공", name: "뷰티매니지먼트과방송스타일디렉터전공", years: 2, tier: 2,
    careers: ["비주얼머천다이징", "패션스타일리스트"],
    promoted: ["비주얼머천다이징", "패션스타일리스트"],
    majorCredits: 63, majorRequired: 45 },
  { id: "뷰티매니지먼트과스킨케어메디컬코스메", name: "뷰티매니지먼트과스킨케어·메디컬코스메", years: 2, tier: 2,
    careers: ["피부미용사"],
    promoted: ["피부미용사"],
    majorCredits: 63, majorRequired: 45 },
  { id: "뷰티매니지먼트과헤어디자인전공", name: "뷰티매니지먼트과헤어디자인전공", years: 2, tier: 2,
    careers: ["헤어디자이너"],
    promoted: ["헤어디자이너"],
    majorCredits: 51, majorRequired: 45 },
  { id: "swd", name: "사회복지과", years: 2, tier: 2,
    careers: ["건강가정사", "사회복지사", "사회복지사/건강가정사", "사회복지사/사회조사분석사"],
    promoted: ["사회복지직 공무원"],
    majorCredits: 64, majorRequired: 45 },
  { id: "sls", name: "사회체육과", years: 2, tier: 2,
    careers: ["스포츠지도사(실기교사)"],
    promoted: ["초·중등학교 실기교사", "스포츠경영 및 마케팅관리자", "전문스포츠 매니저", "휘트니스클럽매니저"],
    majorCredits: 53, majorRequired: 45 },
  { id: "idm", name: "산업경영공학과", years: 2, tier: 2,
    careers: ["물류・유통관리자", "생산・품질관리자"],
    promoted: ["물류・유통관리자", "생산・품질관리자"],
    majorCredits: 57, majorRequired: 45 },
  { id: "iid", name: "산업디자인학과", years: 3, tier: 2,
    careers: ["공간디자이너", "공간디자이너, 제품디자이너", "제품디자이너"],
    promoted: ["공간디자이너", "게임디자인 등 제품디자이너"],
    majorCredits: 104, majorRequired: 66 },
  { id: "tax", name: "세무회계과", years: 2, tier: 2,
    careers: ["공통", "회계·세무사무원"],
    promoted: ["세무사 및 공인회계사"],
    majorCredits: 57, majorRequired: 45 },
  { id: "sileum", name: "실용음악과", years: 2, tier: 2,
    careers: ["실용음악전문인"],
    promoted: ["컴퓨터음악 프로그래머", "음반 기획자"],
    majorCredits: 54, majorRequired: 45 },
  { id: "acting", name: "연극영상학과", years: 3, tier: 2,
    careers: ["공연연출가", "연기자", "연기자, 공연연출가"],
    promoted: ["영화편집기사", "영화사운드디자이너", "조명디자이너"],
    majorCredits: 96, majorRequired: 66 },
  { id: "ece", name: "유아교육학과", years: 3, tier: 2,
    careers: ["영유아교사", "영유아교사, 유아체육지도"],
    promoted: ["유치원 교사", "공사립유치원 교사", "어린이집 교사", "국공립 및 민간어린이집 교사", "교구 제작자"],
    majorCredits: 71, majorRequired: 66 },
  { id: "mjcjp", name: "일본어과", years: 2, tier: 2,
    careers: ["일본비즈니스･서비스전문가", "일본어통･번역콘텐츠융합전문가"],
    promoted: ["일본비즈니스･서비스전문가", "일본어통･번역콘텐츠융합전문가"],
    majorCredits: 60, majorRequired: 45 },
  { id: "electrical", name: "전기공학과", years: 2, tier: 2,
    careers: ["ICT-AI 응용제어운용사", "전기설비시스템실무전문가", "전기제어설계설비원", "전력계통해석및설계사"],
    promoted: ["ICT-AI 응용제어운용사", "전기설비시스템실무전문가", "전기제어설계설비원", "전력계통해석및설계사"],
    majorCredits: 56, majorRequired: 45 },
  { id: "cee", name: "전자공학과", years: 3, tier: 2,
    careers: ["공통", "반도체개발자", "임베디드SW엔지니어"],
    promoted: ["공통", "반도체개발자", "임베디드SW엔지니어"],
    majorCredits: 75, majorRequired: 66 },
  { id: "itc", name: "정보통신공학과", years: 3, tier: 1,
    careers: ["시스템관리·운용엔지니어", "시스템응용SW개발엔지니어"],
    promoted: ["모바일 앱 프로그래머", "웹프로그래머", "게임 프로그래머", "응용프로그램 개발자", "초·중·고 전산 실습 교사", "시스템 엔지니어"],
    majorCredits: 78, majorRequired: 66 },
  { id: "china", name: "중국어비즈니스과", years: 2, tier: 2,
    careers: ["중국관광서비스", "중국교역"],
    promoted: ["중국관광서비스", "중국교역"],
    majorCredits: 54, majorRequired: 45 },
  { id: "jijuk", name: "지적공간정보학과", years: 2, tier: 2,
    careers: ["지적측량인,일반측량인"],
    promoted: ["지적측량인,일반측량인"],
    majorCredits: 60, majorRequired: 45 },
  { id: "yde", name: "청소년교육상담과", years: 2, tier: 2,
    careers: ["청소년상담사", "청소년지도사", "평생교육사"],
    promoted: ["청소년상담사", "청소년지도사", "평생교육사"],
    majorCredits: 69, majorRequired: 45 },
  { id: "mjcd", name: "커뮤니케이션디자인과", years: 2, tier: 2,
    careers: ["공통", "그래픽디자이너/ 브랜드디자이너", "브랜드디자이너/그래픽디자이너"],
    promoted: ["공통", "그래픽디자이너/ 브랜드디자이너", "브랜드디자이너/그래픽디자이너"],
    majorCredits: 54, majorRequired: 45 },
  { id: "mjcs", name: "컴퓨터공학과", years: 3, tier: 2,
    careers: ["모바일콘텐츠개발자", "응용소프트웨어개발자"],
    promoted: ["응용 소프트웨어 개발자", "모바일 콘텐츠 개발자", "웹 솔루션 개발자", "인공지능 개발자", "UX/UI 개발자", "소프트웨어 기획자", "게임 개발자", "게임 기획자", "데이터베이스 엔지니어", "시스템 엔지니어", "네트워크 엔지니어", "보안 솔루션 개발자"],
    majorCredits: 75, majorRequired: 66 },
  { id: "cse", name: "컴퓨터보안공학과", years: 3, tier: 2,
    careers: ["컴퓨터응용시스템개발", "컴퓨터응용시스템전문가", "컴퓨터응용시스템전문가 , 통신및정보호시스템전문가", "컴퓨터응용시스템전문가, 통신및정보보호시스템전문가", "통신및정보보호시스템전문가"],
    promoted: ["정보보안 분야 엔지니어", "통신 및 네트워크 분야 엔지니어", "컴퓨터응용 분야 엔지니어"],
    majorCredits: 82, majorRequired: 66 },
  { id: "civil", name: "토목공학과", years: 2, tier: 2,
    careers: ["스마트건설전문가"],
    promoted: ["토목직종과 관련된 국가공무원"],
    majorCredits: 65, majorRequired: 45 },
  { id: "패션리빙디자인과", name: "패션·리빙디자인과", years: 2, tier: 2,
    careers: ["공통", "리빙상품디자이너", "패션디자이너"],
    promoted: ["패션디자이너", "텍스타일디자이너", "인테리어소품디자이너", "벽지디자이너", "직물분야의 디자이너", "CAD디자이너", "팬시용품디자이너", "액세서리 디자이너", "문화상품디자이너", "리빙상품디자이너", "테이블웨어디자이너", "온라인마켓터 인터넷쇼핑몰 디자이너"],
    majorCredits: 63, majorRequired: 45 },
  { id: "skysvc", name: "항공서비스과", years: 2, tier: 2,
    careers: ["항공객실승무원"],
    promoted: ["항공객실승무원"],
    majorCredits: 63, majorRequired: 45 },
];

export const DEPT_BY_ID = Object.fromEntries(DEPTS.map((d) => [d.id, d]));

/** 학제에 맞는 학년 목록. 2년제는 1~2학년, 3년제는 1~3학년. */
export function yearsOf(dept) {
  return Array.from({ length: dept?.years ?? 3 }, (_, i) => i + 1);
}

/** 교육과정표만으로 전공 요건을 채울 수 없는 학과 — 화면에 사실대로 알린다.
    숨기면 "왜 계속 미달이냐"가 되고, 밝히면 트랙 B(교육과정 진단)의 실제 발견 사례가 된다. */
export function creditGap(dept) {
  if (!dept) return null;
  const short = dept.majorRequired - dept.majorCredits;
  return short > 0 ? { short, have: dept.majorCredits, need: dept.majorRequired } : null;
}
